### ISSUE TITLE
[css] 第106天 CSS中的calc()有什么作用？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1006]
第106天 CSS中的calc()有什么作用？

**Comment by EmiyaYang** [comment]
calc可以让开发者能够使用四则运算表达式来填写CSS属性。

px、%、em等不同单位的数值均可参与计算，浏览器会进行自动转换。

> [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/calc)

**Comment by HuoXiaoYe** [comment]
坑： 当使用calc的时候，运算符号 左右需要有空格的哦，否则，属性不生效。例如： width: calc(100% - 30px);

**Comment by haizhilin2013** [comment]
@HuoXiaoYe 很棒，细节关注得很到位哦！

**Comment by nowherebutup** [comment]
用来计算长宽的属性,非常好用,百分比,px,vh/vm都可参与计算,
不过正如上面的大兄弟说的,运算符的左右要有空格,要不然不生效

**Comment by tiyunchen** [comment]
在less使用中某些情况是无效的```height: calc('100% - 36px');```，
必须要这样才有效 ```height: calc(~'100% - 36px');```

**Comment by qq1255198035** [comment]
> 在less使用中某些情况是无效的`height: calc('100% - 36px');`，
> 必须要这样才有效 `height: calc(~'100% - 36px');`

还需要加单引号吗？

**Comment by Miiskye** [comment]
可以很灵活的计算盒子的长宽，支持加减乘除，单位支持百分比、px、em、rem等，加减运算符左右必须有空格，乘除可以没有，但是一般建议保留空格

**Comment by git710** [comment]
水平垂直居中
```html
<div class="d0">
    <div class=d1""></div>
</div>
```
```css
.d0{
    position: relative;
    width: 300px;
    height: 300px;
    border: 1px solid red;
}
.d1{
    position: absolute;
    width: 100px;
    height: 100px;
    border: 1px solid blue;
    left: calc(50% - 50px);
    top: calc(50% - 50px);
}
```
