### ISSUE TITLE
[html] 第108天 在默认的情况下，使用h1标签呈现出什么效果？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1013]
第108天 在默认的情况下，使用h1标签呈现出什么效果？

**Comment by NicholasBaiYa** [comment]
h1: 块级元素，体字加黑加粗，字号：24px。

**Comment by haizhilin2013** [comment]
> h1: 块级元素，体字加黑加粗，字号：24px。

@NicholasBaiYa 是“字体”
![image](https://user-images.githubusercontent.com/5070345/62335171-55c1ca80-b4fd-11e9-8b29-88aa18b60361.png)

**Comment by EragonBubble** [comment]
> 
    display: block;
    font-size: 2em;
    font-weight: bold;

**Comment by xxf1996** [comment]
我在`chrome`上看到是这个效果：
```css
h1 {
    display: block;
    font-size: 2em;
    margin-block-start: 0.67em;
    margin-block-end: 0.67em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    font-weight: bold;
}
```
当然，有的地方使用`font-size: 2rem;`来控制`h1`标签的字体大小；
