### ISSUE TITLE
[js] 第137天 用js实现页面局部打印和预览原理是什么呢？同时在IE上有什么不同？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1134]
第137天 用js实现页面局部打印和预览原理是什么呢？同时在IE上有什么不同？

**Comment by bowencool** [comment]
替换html为目标DOM，调用window.print()之后，再还原原始DOM。

**Comment by xiaotianxia** [comment]
```css
@media print {
    *:not(.somedom) {
         display: none;
    }
}
```
这样吗
