### ISSUE TITLE
[html] 第143天 请说说<pre>和<code>标签的区别？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1157]
第143天 请说说 `<pre>` 和 `<code>` 标签的区别？

**Comment by EchoWht** [comment]
< pre> 里的内容会保留换行符和空格，<code>里的不会保留

**Comment by xxf1996** [comment]
看了下谷歌浏览器关于这两个标签的用户样式：
- `<code>`：
```css
code {
    font-family: monospace;
}
```
- `<pre>`：
```css
pre {
    display: block;
    font-family: monospace;
    white-space: pre;
    margin: 1em 0px;
}
```
不难看出`code`标签仅仅是给文字设置了浏览器的默认等宽字体；而`pre`标签默认的`white-space`属性值是`pre`，即保留连续空白符；
