### ISSUE TITLE
[html] 第149天 怎样把整个页面中的内容设置成只读，不可编辑的状态？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1182]
第149天 怎样把整个页面中的内容设置成只读，不可编辑的状态？

**Comment by zhangdxiuxiu** [comment]
readonly

**Comment by ch-liuzhide** [comment]
1.将所有dom设置为disabled
2.搞个透明，全屏的最上层的div元素
3.想编辑，先过了我input事件再说

**Comment by foreverZ133** [comment]
突然想到个骚方法，focus 时立马触发 blur，嘿嘿

**Comment by zhengyanghou** [comment]
发的第三方三

**Comment by ferrinweb** [comment]
```css
body {
  pointer-events: none !important;
}
```
