### ISSUE TITLE
[css] 第152天 如何使用CSS的多列布局？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1206]
第152天 如何使用CSS的多列布局？

**Comment by NicholasBaiYa** [comment]
```css
div {
    -webkit-column-count: 3; /* Chrome, Safari, Opera */
    -moz-column-count: 3; /* Firefox */
    column-count: 3;
}
```
或者使用flex布局来实现多列布局
