### ISSUE TITLE
[css] 第162天 移动端的布局用过媒体查询吗？写一个试试

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1256]
第162天 移动端的布局用过媒体查询吗？写一个试试

**Comment by NicholasBaiYa** [comment]
```css
@media (max-width: 600px) {
  .facet_sidebar {
    color: red;
  }
}
```
