### ISSUE TITLE
[css] 第164天 你是怎么选择resetting和normalizing的？为什么？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1264]
第164天 你是怎么选择resetting和normalizing的？为什么？

**Comment by HCLQ** [comment]
两者都是统一不同浏览器默认样式
resetting 是减法
normalizing 是加法
我选加法
减法意味没有浏览器默认样式，全部样式自己写，甭管用不用的到的元素
加法抹平差异，只有你一些用到的要自己写，其他默认样式比如行高还是有必要的

**Comment by vkboo** [comment]
* 一般选择normalize
* Reset: 比较粗暴的处理方式，不管有用没有统统处理成一种方式，如果是临时页面会采用。
```css
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
*::after,
*::before {
    box-sizing: border-box;
}
```
* Normalize: Normalize注重通用的方案，重置掉该重置的样式，保留有用的 user agent 样式，同时进行一些 bug 的修复，这点是 reset 所缺乏的。
