### ISSUE TITLE
[css] 第168天 怎么去掉点击a链接或者图片出现的边框？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1280]
第168天 怎么去掉点击a链接或者图片出现的边框？

**Comment by Davidyanlong** [comment]
a{text-decoration:none}
img{border:0  none}

**Comment by vkboo** [comment]
* Demo
```CSS
a:active,
img:active {
    border: none;
    outline: none;
    text-decoration: none;  
}
```
