### ISSUE TITLE
[css] 第35天 使用flex实现三栏布局，两边固定，中间自适应

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#129]
第35天 使用flex实现三栏布局，两边固定，中间自适应

**Comment by xiangshuo1992** [comment]
这就是圣杯布局国内也叫双飞翼布局，在第一天已经有回答了

[第1天 圣杯布局和双飞翼布局的理解和区别，并用代码实现](https://github.com/haizlin/fe-interview/issues/2)

同意里面的一个回答，现在有很多简单的实现方式，传统的这个也是一种hack的方式，真的没必要去追究了，但是核心知识点可以掌握。

1.把 center 放在最前面，优先渲染
2.相对定位 relative 也是可以设置 left,right等值的
3.margin 负值的了解和使用
4.float 真的不建议使用

现在的flex/grid很轻松就能实现，甚至绝对定位也是很容易实现也更容易理解。

**Comment by tzjoke** [comment]
```html
<div class="container">
  <section class="left red"></section>
  <main class="middle blue"></main>
  <section class="right red"></section>
</div>
```

```css
.container {
  width: 100%;
  height: 100%;
  display: flex;
}

.left,
.right {
  flex: 0 0 auto;
  width: 50px;
  height: 100%;
}

.middle {
  flex: 1 1 auto;
  height: 100%;
}

.red {
  background-color: red;
}

.blue {
  background-color: blue;
}
```

**Comment by Vi-jay** [comment]
```scss
.container {
      display: flex;
      height: 100px;
      .left, .right {
        width: 100px;
        background: #8c939d;
      }
      .content {
        flex: 1;
        background: #306eff;
      }
    }
```
