### ISSUE TITLE
[css] 第182天 让你手写一个reset的文件，你应该怎么写？要考虑哪些方面呢？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1372]
第182天 让你手写一个reset的文件，你应该怎么写？要考虑哪些方面呢？

#1042，#1264

**Comment by mjhcc365** [comment]
肯定首先考虑的是浏览器本身的样式，还有浏览器兼容。

- margin，padding ==>0
- ul,ol list style:none
- a,text-decoration:none
- font-size:100%
- 上标，下标。表格等

**Comment by liugezhou** [comment]
#### CSS reset，又叫做 CSS 重写或者 CSS 重置，用于改写HTML标签的默认样式。
> 进行样式重写时，不建议使用 * 选择器进行重写，这样会降低效率，影响性能.

> 样式重写可参考：https://meyerweb.com/eric/tools/css/reset/:
```
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header,
menu, nav, output, ruby, section, summary,
time, mark, audio, video, input
  margin: 0
  padding: 0
  border: 0
  font-size: 100%
  font-weight: normal
  vertical-align: baseline

/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure,
footer, header, menu, nav, section
  display: block

body
  line-height: 1

blockquote, q
  quotes: none

blockquote:before, blockquote:after,
q:before, q:after
  content: none

table
  border-collapse: collapse
  border-spacing: 0

/* custom */

a
  color: #7e8c8d
  -webkit-backface-visibility: hidden
  text-decoration: none

li
  list-style: none

body
  -webkit-text-size-adjust: none
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0)
```

**Comment by vkboo** [comment]
reset主要是用来尽量抹平个浏览器的样式差异，以及重置一些日常使用的样式(如`li`)，所以在写的时候，各种常用的标签都要考虑到，同时也要考虑到性能，不要去使用`*`选择器等。
demo: 
```CSS
/* http://meyerweb.com/eric/tools/css/reset/
   v4.0 | 20180602
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, menu, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
main, menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure,
footer, header, hgroup, main, menu, nav, section {
	display: block;
}
/* HTML5 hidden-attribute fix for newer browsers */
*[hidden] {
    display: none;
}
body {
	line-height: 1;
}
menu, ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```
