### ISSUE TITLE
[css] 第38天 实现单行文本居中和多行文本左对齐并超出显示"..."

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#141]
第38天 实现单行文本居中和多行文本左对齐并超出显示"..."

**Comment by wenyejie** [comment]
```css

.one {
  text-align: center
}

.multi {
  overflow: hidden
  text-overflow: ellipsis
  display: -webkit-box
  -webkit-line-clamp: 3
  -webkit-box-orient: vertical
}
```

可惜多行文本省略, 有严重的兼容性问题

**Comment by rocky-191** [comment]
> ```css
> .one {
>   text-align: center
> }
> 
> .multi {
>   overflow: hidden
>   text-overflow: ellipsis
>   display: -webkit-box
>   -webkit-line-clamp: 3
>   -webkit-box-orient: vertical
> }
> ```
> 
> 可惜多行文本省略, 有严重的兼容性问题

是啊，谷歌内核的才支持这个写法

**Comment by tzjoke** [comment]
@rocky-191 ff68支持了

**Comment by tzjoke** [comment]
@wenyejie 多行溢出不需要 `text-overflow: ellipsis` 吧

**Comment by DarthVaderrr** [comment]
多行文本溢出目前没有解决方案

**Comment by Vi-jay** [comment]
```scss
 .container {
      text-align: center;
      height: 100px;
      width: 100px;
      overflow: hidden;
      word-break: break-all;
      .content{
        text-align: left;
        display: inline-block;
      }
    }
```
ps:实现了单行居中 多行居左 但是没办法并且超出显示...  估计是用伪元素遮住最后几个文字显示...

**Comment by jiamianmao** [comment]
愚兄前些年看过篇文章，与众贤弟分享一下。
[单行居中显示文字，多行居左显示，最多两行超过用省略号结尾](https://github.com/chokcoco/iCSS/issues/50)

**Comment by fntst** [comment]
[多行显示非Chrome只能使用JS来完成了啊, 写的一个方法 供参考,哈哈 ](https://github.com/fntst/tlfns/blob/master/src/utils/multiRowsEllipsis.js)

用法如下:
```
multiRowsEllipsis(elem,rows=2,sym='...',autoMode=true)   // 多行省略号,返回最终的字符串  
    elem      显示文本的且需设置多行省略的元素 
    rows      行数 
    sym       省略号字符串 
    autoMode  是否自动改变 [vue中需交给vue来维护,将返回最终的字符串重新赋值到文本显示区]

```

**Comment by Konata9** [comment]
- 单行文本居中。在 `webkit` 内核中适用。非 `webkit` 内核，可以是用 js 或者用 `::after` 模拟。
	```css
	.single-text{
		width: 500px;
		font-size: 18px;
		font-weight: bold;
		text-align: center;
		color: white;
		background: lightblue;
		display: box;
		white-space: nowrap;
		overflow:hidden;
		text-overflow: ellipsis;
	}
	```

- 多行文本左对齐。多行文本没有很好的解决方法，只能依赖 js 或者 css 的相对定位。
	```css
	.multi-text{
		width: 50%;
		height: 4.5rem;
		line-height: 1.5;
		padding: 20px;
		background: lightblue;
		overflow: hidden;
		position: relative;
		box-sizing: border-box;
		
		&::after{
			content: '...';
			height: 1.5rem;
			position: absolute;
			bottom: 5px;
			right: 5px;
		}
	}
	```

示例代码：https://codepen.io/Konata9/pen/RwbYbRG

**Comment by canwdev** [comment]
[可能是最全的 “文本溢出截断省略” 方案合集 - 掘金](https://juejin.im/post/5dc15b35f265da4d432a3d10)

**Comment by 1282772905** [comment]
```less
.linex(@num) {
  display: -webkit-box;
  overflow: hidden;
  word-break: break-all;

  -webkit-box-orient: vertical;
  -webkit-line-clamp: @num;
}
```
