### ISSUE TITLE
[css] 第194天 你最希望css拥有什么样的特性？（目前没有的）

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1445]
第194天 你最希望css拥有什么样的特性？（目前没有的）

**Comment by wheatup** [comment]
自定义css变量的animation和transition支持

**Comment by foreverZ133** [comment]
父类选择器吧，:focus-within 在 focus 时能修改父类样式，
如果默认就能修改父类样式那就太棒了。

**Comment by wheatup** [comment]
`:nth-letter` 选择器
`:has` 选择器（似乎快了）

以及如果能实现这些我就不需要sass了：
```css
ul {
  counter-reset: lis;
}

ul li{
  counter-increment: lis;
  /* counter 可以用计算 */
  width: calc(lis * 200px);
  /* attr 可以用于计算 */
  height: calc(attr(data-height) * 1rem);
}
```
