### ISSUE TITLE
[css] 第39天 写出你知道的CSS水平和垂直居中的方法

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#145]
第39天 写出你知道的CSS水平和垂直居中的方法

**Comment by git710** [comment]
flex布局水平垂直居中:

```html
<!--  html -->
<div class="outer">
    <div class="inner"></div>
</div>
```
```css
/*css*/
.outer{
    display:flex;
    width:200px;
    height:200px;
    border:1px solid red;
}
.inner{
    width:100px;
    height:100px;
    border:1px solid blue;
    margin:auto;
}
```

**Comment by wenyejie** [comment]
```html
<div class="parent">
  <div class="child" />
</div>
```

```css
.parent {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

**Comment by xiangshuo1992** [comment]
这个就多了，分为水平居中，垂直居中，水平垂直居中。
可以看下我之前整理的：[还不会CSS水平垂直居中？这里有12种方案](https://xiangshuo.blog.csdn.net/article/details/86539582)

然后呢，后来发现有个同学整理的比我更多
[如何居中一个元素（终结版）](https://juejin.im/post/5bc3eb8bf265da0a8a6ad1ce#comment)

针对上面的整理，我还补充了一条

[已知宽高，利用绝对定位来居中](https://codepen.io/xiangshuo1992/pen/YgYqpK)

**Comment by rocky-191** [comment]
水平垂直居中，flex布局，定位布局（absolute+margin）| (asbolute+transform)也可以实现。text-align:center水平居中，这种方案还有好多种。

**Comment by tzjoke** [comment]
完全居中常用两种方案：
1. 绝对布局
```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```

2. flexbox

```css
.parent {
    display: flex;
    justify-content: center;
    align-items: center;
}
```
