### ISSUE TITLE
[css] 第198天 如何使用CSS实现段落首字母或首字放大效果？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1461]
第198天 如何使用CSS实现段落首字母或首字放大效果？

**Comment by wheatup** [comment]
`::first-letter` 伪元素选择器

```css
p::first-letter {
  font-size: 2em;
  font-weight: bold;
}
```

**Comment by vkboo** [comment]
```javascript
.zh::first-letter {
        font-weight: bold;
        font-size: 24px;
    }
```

**Comment by foreverZ133** [comment]
![image](https://user-images.githubusercontent.com/22021589/67927118-c3f85500-fbf2-11e9-9270-21804acb353a.png)
一般使用 em 单位，再加上 float，可实现上图效果。

**Comment by everest2015** [comment]
方法一：
伪元素选择器
```
div::first-letter {
   font-size: 24px;
   font-weight: bold;
}
```

方法二：

```css
div {
text-transform: capitalize;
}
<div>
i come from China
</div>
```
