### ISSUE TITLE
[css] 第204天 手写一个使用css3旋转硬币的效果

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1485]
第204天 手写一个使用css3旋转硬币的效果

**Comment by zhazhapeng** [comment]
两种实现方式：1、animation+keyframes   2、transition：
//第一种实现方式
<style type="text/css">
.around{
width:200px;
height:200px;
background:orange;
/*圆形的话看不出效果，所以这里border-radius没有取50%*/
border-radius:40%;
transform:rotate(0deg);
animation:move 3s ease;
}
@keyframes move{
0%{
 transform:rotate(0deg);
 }
50%{
 transform:rotate(360deg);
}
100%{
 transform:rotate(0deg);
}
}
</style>

//第二种实现方式
<style type="text/css">
.around{
width:200px;
height:200px;
background:orange;
/*圆形的话看不出效果，所以这里border-radius没有取50%*/
border-radius:40%;
transform:rotate(0deg);
transition:transform 3s linear;
}
.around:hover{
transform:rotate(360deg);
}

</style>

**Comment by censek** [comment]
```css
 .coin {
    width: 100px;
    height: 100px;
    margin: 100px;
    animation: rotate 5s linear;
    background-color: goldenrod;
    border-radius: 50%;
  }

  .coin:hover {
    animation-play-state: paused;
  }

  @keyframes rotate {
    0% {
      transform: rotateY(0deg);
    }

    100% {
      transform: rotateY(360deg);
    }
  }
```
```html
 <div class="coin" style="transform: translateZ(1px);"></div>
```
