### ISSUE TITLE
[css] 第40天 怎么才能让图文不可复制？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#149]
第40天 怎么才能让图文不可复制？

**Comment by rocky-191** [comment]
-webkit-user-select: none; 
-ms-user-select: none;
-moz-user-select: none;
-khtml-user-select: none;
user-select: none;

**Comment by tzjoke** [comment]
postcss + user-select: none;  😆

**Comment by Alan201601** [comment]
user-select:none

**Comment by 542154968** [comment]
[禁止用户打开浏览器控制台](https://www.jianshu.com/p/1c171cb86dbb)

**Comment by Konata9** [comment]
利用 `user-select: none` 属性，让元素不能被选中。

**Comment by CoderLeiShuo** [comment]
- 禁止复制+剪切
- 禁止右键，右键某些选项：全选、复制、粘贴等
- 禁用文字选择，能选择却不能复制，体验很差
- `user-select`用`css`禁止选择文本

```js
// 禁止右键菜单
document.body.oncontextmenu = e => {
    return false;
    // e.preventDefault();
}
// 禁止文字选择
document.body.onselectstart = e => {
    return false;
    // e.preventDefault();
}
// 禁止复制
document.body.oncopy = e => {
    return false;
    // e.preventDefault();
}
// 禁止粘贴
document.body.onpaste = e => {
    return false;
    // e.preventDefault();
}
```

CSS方式：

```css
/* CSS禁止文本选择，这样不会触发js */
body {
       user-select: none;
       -webkit-user-select: none;
       -moz-user-select: none;
       -ms-user-select: none;
       -o-user-select: none;
      }
```

使用`e.preventDefault()`也可以禁用，但建议使用`return false`这样就不用去访问`e`和`e`的方法了。

示例中`document.body`全局都禁用了，也可以对`dom`（某些区域）进行禁用

来源：[JavaScript中的复制粘贴功能](http://blog.poetries.top/2018/12/23/js-copy/#2-2-%E9%98%B2%E5%A4%8D%E5%88%B6%E5%8A%9F%E8%83%BD)
