### ISSUE TITLE
[css] 第214天 实现文本的竖向排版

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1526]
第214天 实现文本的竖向排版

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by xgqfrms** [comment]
```css
.{
    direction: rtl;
}

```
