### ISSUE TITLE
[css] 第41天 怎么让英文单词的首字母大写？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#153]
第41天 怎么让英文单词的首字母大写？

**Comment by wenyejie** [comment]
```css
.demo {
  text-transform: capitalize;
}
```
