### ISSUE TITLE
[css] 第216天 怎么让div中的图片和文字同时上下居中？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1534]
第216天 怎么让div中的图片和文字同时上下居中？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by luojiyin1987** [comment]
添加CSS属性：vertical-align:middle

**Comment by everast2015** [comment]
```html
<div>
  <img src="./"/>
 <label>文字内容</label>
</div>
```
```css
<style>
 img {
    vertical-align: middle;
}
</style>
```
给 img 设置 `vertical-align: middle;` 并且 `vertical-align` 只对行内元素，还有表格内的单元格有效，对块级元素的垂直居中是没有任何效果的
[MDN 文档说明](https://developer.mozilla.org/zh-CN/docs/Web/CSS/vertical-align)
