### ISSUE TITLE
[css] 第217天 举例说明:not()的使用场景有哪些

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1538]
第217天 举例说明:not()的使用场景有哪些

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by Lanbasara** [comment]
可以理解为反向选择器
举例：
    <p>1</p>
    <p>2</p>
    <p id="strong">33333</p>
<style>
    p:not(#strong){
        color:red;
    }
</style>

可以直接选择到前两个p元素

**Comment by everast2015** [comment]
`:not` 伪类，匹配到不符合条件一组选择器
```css
:not(p) {
color: wheat; // 除了 p 选择器之外，其他的元素的字体颜色都设置为小麦色
}
```
