### ISSUE TITLE
[css] 第236天 移动端页面不满一屏时如何实现满屏背景？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1617]
第236天 移动端页面不满一屏时如何实现满屏背景？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by wheatup** [comment]
```css
body {
  min-height: 100vh;
}
```
