### ISSUE TITLE
[css] 第44天 手写一个满屏品字布局的方案

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#166]
第44天 手写一个满屏品字布局的方案

**Comment by tzjoke** [comment]
整体100%高度，上面50高度margin auto居中，下面50%高度俩float一半宽度。。应该符合题意把

**Comment by DingkeXue** [comment]
flex布局

**Comment by zhuyuedlut** [comment]
用grid布局是否好点

**Comment by 1018715564** [comment]
<!DOCTYPE html>
<html>

<head>
	<title>Parcel Sandbox</title>
	<meta charset="UTF-8" />
	<style>
		.box {
            width: 100%;
            justify-content: center;
			display: flex;
			
			flex-wrap: wrap;
		}
		.top {
			flex: 50px 0 0;
            width: 100px;
            height: 100px;
            background: red;
            flex-grow: 3;
            font-size: 18px;
            color: #fff;
            text-align: center;
		}
		.bottom {
            width: 100%;
            
			display: flex;
		}
        .bottom-first {
            width: 50%;
            background: blue;
        }
        .bottom-second{
            width: 50%;
            background: orange;
        }
	</style>
</head>

<body>
	<div class="box">
		<div class="top">top</div>
		<div class="bottom">
			<div class="bottom-first">first</div>
			<div class="bottom-second">second</div>
		</div>
	</div>
</body>

</html>

**Comment by ipadthree** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <article class="container">
            <div class="firstRow">
                <div class="item"></div>
            </div>
            <div class="secondRow">
                <div class="item"></div>
                <div class="item"></div>
            </div>
        </article>
    </body>
</html>
```


```css
//style.css
html, body{
    height: 100%;
    margin: 0;
    padding: 0;
}
 
.container {
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    width: 100%;
    height: 100%;
}

.firstRow, .secondRow {
    width: 100%;
    height: 30%;
    display: flex;
    flex-direction: row;
    justify-content: center;
    margin: 10px 0;
}

.item {
    background-color: red;
    width: 40%;
    height: 100%;
    margin: 0 auto;
    border-radius: 10%;
}
```
