### ISSUE TITLE
[css] 第254天 如何使用CSS绘制一个汉堡式菜单

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1695]
第254天 如何使用CSS绘制一个汉堡式菜单

作者：cxwht

[我也要出题](http://web.haizlin.cn/interview/)

使用CSS绘制一个汉堡式菜单，即选单按钮上的三条平行横线图标

**Comment by wheatup** [comment]
比较常见的两种方法：
* 利用元素自身、`::before`和`::after`伪元素绘制3个长宽一致的矩形，然后设定其y偏移值。
* 利用上下`border`和自身元素内容绘制：
```css
.burger {
	--width: 20px;
	--thickness: 4px;
	--color: black;
	
	display: inline-block;
	width: var(--width);
	height: var(--thickness);
	background-color: var(--color);
	background-clip: content-box;
	border-top: solid var(--thickness) var(--color);
	border-bottom: solid var(--thickness) var(--color);
	padding-top: var(--thickness);
	padding-bottom: var(--thickness);
}
```

**Comment by forever-z-133** [comment]
```scss
/* 需要父级设定高度，嘤嘤嘤 */
/* 汉堡式菜单图标，宽高尺寸，线条粗细，线条颜色 */
@mixin menu($size: 50px, $thick: 3px, $color: #000) {
  $_size: $size / 2 - $thick;
  width: 50px;
  height: 0;
  color: $color;
  box-shadow:  0 0 0 $thick $color, 0 -1 * $_size 0 $thick $color,  0 $_size 0 $thick $color;
}
.menu { @include menu(); }
```
