### ISSUE TITLE
[css] 第45天 你知道的等高布局有多少种？写出来

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#170]
第45天 你知道的等高布局有多少种？写出来

**Comment by wenyejie** [comment]
现在肯定是flex咯
我记得以前还有一种方案, `padding: 10000px; margin: -10000px`大概是这样! 
要不然就通过js去控制

**Comment by cleverboy32** [comment]
flex ;

.wrap > * { height: 100%; }

**Comment by Vi-jay** [comment]
1.  flex拉伸

   ```css
   display: flex;
   align-items: stretch;
   ```

   2. padding margin抵消 然后background-clip默认是padding-box所以会在被抵消的位置依然显示背景 造成等高假象

   ```css
   .box,.box2{
       float: left;
       width: 100px;
   }
   .box {
       background: #cccccc;
       height: 300px;
   }
   .box2 {
       background: #306eff;
       padding-bottom: 99999px;
       margin-bottom: -99999px;
   }
   ```
