### ISSUE TITLE
[html] 第281天 写个布局，当页面高度不够时，底部固定在下面，反之不固定

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1804]
第281天 写个布局，当页面高度不够时，底部固定在下面，反之不固定

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by forever-z-133** [comment]
https://codepen.io/foreverZ133/pen/VwYREVM

**Comment by censek** [comment]
```html
<div class="layout"> 
    <header class="header">
     <!-- header 内容 …… -->
    </header>
    <div class="page">
      <slot />
    </div>
    <footer class="footer">
      <!-- footer 内容 …… -->
    </footer>
</div>
```
```css
.layout {
  position: relative;
  min-height: 100%;
}
.page {
  padding-bottom: 45px;
}
.footer {
  color: #c5c5c5;
  position: absolute;
  bottom: 20px;
  height: 25px;
}
```
