### ISSUE TITLE
[html] 第309天 如何解决input在Firefox和Chrome中高度不一致的问题？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1928]
第309天 如何解决input在Firefox和Chrome中高度不一致的问题？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by longhui520** [comment]
- 原因是firefox的input的border-width padding 受win10系统的文本大小设置影响
- 设置一样的样式
    ```css
    input{
        box-sizing:border-box;
        height:20px;
    }
    ```
- 将win10 系统的文本大小设置为100%
