### ISSUE TITLE
[css] 第309天 如何让IE6支持min-width和max-width？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1929]
第309天 如何让IE6支持min-width和max-width？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by longhui520** [comment]
- 利用IE特有的css语法
    ```css
    .className {
        max-width:620px;
        min-width:1px;
        _width:expression(this.scrollWidth > 620 ? "620px":(this.scrollWidth < 1? "1px":"auto"));
    }
    ```
- [参考文章](https://www.jb51.net/css/76142.html)
