### ISSUE TITLE
[css] 第316天 如何给文字的color设置渐变

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1964]
第316天 如何给文字的color设置渐变

作者：cxwht

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by gaoryrt** [comment]
webkit only
```css
.text {
  background: -webkit-linear-gradient(#eee, #333);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
```

**Comment by longhui520** [comment]
```html
     span {
        background: linear-gradient(to right, red, blue);
        -webkit-background-clip: text;
        color: transparent;
    }
   ```

**Comment by forever-z-133** [comment]
还可以用 `-webkit-mask`。

还有种非常特殊的场景可以看下例，类似于视觉残留：
https://forever-z-133.github.io/demos/single/gradient-mask-word2.html

**Comment by censek** [comment]
```html
 <p class="text">The background is clipped to the foreground text.</p>
```

```css
  p {
      background: linear-gradient(60deg, red, yellow, red, yellow, red);
  }
  .text {
      background-clip: text;
      -webkit-background-clip: text;
      color: rgba(0, 0, 0, .2);
  }
```
