### ISSUE TITLE
[css] 第318天 你有没有使用过“形似猫头鹰”（例：`* + *{ ... }`） 的选择器？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1973]
第318天 你有没有使用过“形似猫头鹰”（例：`* + *{ ... }`） 的选择器？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by wheatup** [comment]
以前常用，比如
```css
li + li {
	margin-top: 1rem;
}
```
这样可以给除了第一个`li`以外的`li`指定样式，比如在两个`li`之间加上`margin`

---

现在大多这么写：
```css
li:not(:first-of-type) {
	margin-top: 1rem;
}
```
可以达到一样的效果
