### ISSUE TITLE
[css] 第320天 使用纯css来创建一个滑块

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1982]
第320天 使用纯css来创建一个滑块

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by longhui520** [comment]
```css
     .checke{
            position: relative;
            -webkit-appearance: none;
            width:90px;
            height: 44px;
            line-height: 44px;
            background: #eee;
            border-radius: 30px;
            outline: none;
        }
        .checke:before{
            position: absolute;
            left: 0;
            content: '';
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: #eee;
            box-shadow: 0px 0px 5px #ddd;
            transition: all 0.2s linear;
        }
 
        .checke:checked{
           background: #18ff0a;
        }
        .checke:checked:before{
            left: 45px;
            transition: all 0.2s linear;
        }
  ```
