### ISSUE TITLE
[css] 第321天 使用css3实现一个斑马线的效果

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1986]
第321天 使用css3实现一个斑马线的效果

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by ferrinweb** [comment]
```css
.banmaxian {
  position: fixed;
  bottom: 15px;
  right: 15px;
  width: 20px;
  height: 200px;
  box-shadow: #f2f2f2 -40px 0 0, #f2f2f2 -80px 0, #f2f2f2 -120px 0;
  z-index: 999999999;
  background: #f2f2f2;
}
```

**Comment by longhui520** [comment]
```css
    /*背景斑马线*/
     p {
            font-size: 17px;
            line-height: 25px;
            background-color: antiquewhite;
            background-image: linear-gradient(#999999 50%, transparent 0);
            background-size: auto 50px;
            background-origin: content-box;
        }
   ```

**Comment by cxwht** [comment]
我觉得也可以使用 nth-child(odd / even) 来实现这个效果，毕竟斑马线就是黑白相间的吗

**Comment by xiangshuo1992** [comment]
1. @ferrinweb 如果需要很多或者无限扩展的斑马线，你这个方案就有缺点了
2. @cxwht 你的方案需要增加额外的元素，不太理想
3. 最好的办法是用渐变背景实现
```
linear-gradient( [ [ <angle> | [top | bottom] || [left | right] ],]? <color-stop>[, <color-stop>]+);
/*角度|方向、开始颜色 开始位置、结束颜色 结束位置*/
```
我们将开始位置与结束位置设置为相等或大于，就可以得到条纹图案。

示例：https://codepen.io/xiangshuo1992/pen/qLdWdY （含11个demo）

1. 水平条纹

```css
{
    background: linear-gradient(#fb3 33.3%,
                #58a 0, #58a 66.6%, yellowgreen 0);
    background-size: 100% 45px;
}
```

2. 垂直条纹

```css
{
    background: linear-gradient(to right, /* 或 90deg */
                #fb3 50%, #58a 0);
    background-size: 30px 100%;
}
```

3. 45deg斜条纹

```css
{
    background: linear-gradient(45deg,
                #fb3 25%, #58a 0, #58a 50%,
                #fb3 0, #fb3 75%, #58a 0);
    background-size: 30px 30px;
}

/*计算准确的15px宽斜条纹*/
{
    background: linear-gradient(45deg,
                #fb3 25%, #58a 0, #58a 50%,
                #fb3 0, #fb3 75%, #58a 0);
    background-size: 42.43px 42.43px;
}
```

4. 更好的斜向条纹

```css
/*循环渐变实现斜条纹*/
{
    background: repeating-linear-gradient(45deg,
                #fb3, #fb3 15px, #58a 0, #58a 30px);
}

/*两种方式结合*/
{
    background: repeating-linear-gradient(45deg,
                #fb3 0, #fb3 25%, #58a 0, #58a 50%);
    background-size: 42.43px 42.43px;
}
```

5. 灵活的同色系条纹

```css
{
    background: #58a;
    background-image: repeating-linear-gradient(30deg,
                      hsla(0,0%,100%,.1),
                      hsla(0,0%,100%,.1) 15px,
                      transparent 0, transparent 30px);
}
```
