### ISSUE TITLE
[css] 第322天 如何使用css实现跨浏览器的最小高度？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#1995]
第322天 如何使用css实现跨浏览器的最小高度？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by longhui520** [comment]
```css
    div{
        height:auto!important; 
        height:200px; 
        min-height:200px; 
    }
   ```
