### ISSUE TITLE
[css] 第325天 如何禁用移动的选择高亮？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2012]
第325天 如何禁用移动的选择高亮？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by longhui520** [comment]
```css
    *{ -webkit-tap-highlight-color: rgba(0,0,0,0);
       -webkit-tap-highlight-color: transparent; /* For some Androids */ 
    }
   ```
    [参考资料](https://www.cnblogs.com/xutongbao/p/9924823.html)
