### ISSUE TITLE
[html] 第327天 如何禁止移动端的左右划动手势？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2019]
第327天 如何禁止移动端的左右划动手势？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by longhui520** [comment]
```css
    html{
    touch-action:none;
    touch-action:pan-y;
    }
   ```
   - [参考文章](https://blog.csdn.net/qq_37028216/article/details/88310634)
