### ISSUE TITLE
[css] 第337天 使用css的attr()写一个类似a标签title的提示框

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2086]
第337天 使用css的attr()写一个类似a标签title的提示框

#220

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by longhui520** [comment]
```css
    .box{
        position:relative;
    }
    .box:hover{
        content: attr(data-title);    
        display: inline-block;
        padding: 10px 14px;
        border: 1px solid #ddd;
        border-radius: 5px;
        position: absolute;
        top: -50px;
        left: -10px;
    }
  ```
