### ISSUE TITLE
[css] 第338天 举例说明如何从html元素继承box-sizing？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2090]
第338天 举例说明如何从html元素继承box-sizing？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by wheatup** [comment]
通常的做法：
```css
*, *::before, *::after {
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}
```

**Comment by longhui520** [comment]
```css
    html{
        box-sizing:border-box;
    }
    *,*:before,*:after{
        box-sizing:inherit;
    }
   ```
