### ISSUE TITLE
[html] 第358天 给一个元素加下划线的方法有哪些？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2204]
第358天 给一个元素加下划线的方法有哪些？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by a298003154** [comment]
1. 使用 `<u></u>` 标签
2. 给元素添加 `boder-bottom`
2. 使用伪类或者子元素做绝对定位
```css
.target {
  position: relative;
}
.underline {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 1px;
  background-color: black;
}
```
