### ISSUE TITLE
[css] 第365天 用css画出一个圆圈，里面有个对号

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2245]
第365天 用css画出一个圆圈，里面有个对号

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by RookieGz** [comment]
```css
#right {
        width: 150px;
        height: 150px;
        margin: 100px auto;
        border-radius: 50%;
        border: 5px solid #000000;
        display: flex;
        justify-content: center;
        align-items: center;
      }
      #right::before {
        content: "";
        display: block;
        width: 88px;
        height: 50px;
        border: 20px solid #000000;
        border-right: none;
        border-top: none;
        transform: rotate(-45deg) translate(7px, -10px);
      }
```
