### ISSUE TITLE
[css] 第366天 用css画出一个圆圈，里面有个叉号（不能用英文字母x）

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2247]
第366天 用css画出一个圆圈，里面有个叉号（不能用英文字母x）

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by RookieGz** [comment]
```css
#cyc {
        width: 150px;
        height: 150px;
        margin: 100px auto;
        border-radius: 50%;
        border: 5px solid #000000;
        position: relative;
      }

      #cyc::before {
        content: "";
        display: block;
        width: 100px;
        height: 20px;
        background: #000;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(45deg);
      }
      #cyc::after {
        content: "";
        display: block;
        width: 100px;
        height: 20px;
        background: #000;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-45deg);
      }
```

``html
<div id="cyc"></div>
```
