### ISSUE TITLE
[html] 第369天 实现一个stick-footer布局

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2258]
第369天 实现一个stick-footer布局

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by censek** [comment]
```html
<div class="layout"> 
    <header class="header">
     <!-- header 内容 …… -->
    </header>
    <div class="page">
      <slot />
    </div>
    <footer class="footer">
      <!-- footer 内容 …… -->
    </footer>
</div>
```
```css
.layout {
  position: relative;
  min-height: 100%;
}
.page {
  padding-bottom: 45px;
}
.footer {
  color: #c5c5c5;
  position: absolute;
  bottom: 20px;
  height: 25px;
}
```
