### ISSUE TITLE
[css] 第381天 使用css实现一个loading的效果

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2316]
第381天 使用css实现一个loading的效果

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by censek** [comment]
```html
<div class="donut"></div>
```
```css
@Keyframes donut-spin {
   0% {
     transform: rotate(0deg);
   }

   100% {
     transform: rotate(360deg);
   }
}

.donut {
   display: inline-block;
   border: 4px solid rgba(0, 0, 0, 0.1);
   border-left-color: #59a782;
   border-radius: 50%;
   width: 30px;
   height: 30px;
   animation: donut-spin 1.2s linear infinite;
}
```
