### ISSUE TITLE
[css] 第385天 使用css实现霓虹灯效果

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2332]
第385天 使用css实现霓虹灯效果

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by zhaofeipeter** [comment]
text-shadow:0 0 3px #FF0000;

**Comment by censek** [comment]
```html
  <div class="neon">Good evening, and good night!</div>
```
```css
  body {
    display: flex;
    height: 100vh;
    justify-content: center;
    align-items: center;
    text-align: center;
    background: black;
  }

  .neon {
    color: #cce7f8;
    font-size: 2.5rem;
    font-family: 'Pacifico', cursive;
    text-transform: uppercase;
    animation: shining 0.1s alternate infinite;
  }

  @keyframes shining {
    from {
      text-shadow: 0 0 6px rgba(182, 211, 207, 0.9),
        0 0 30px rgba(182, 211, 207, 0.3), 0 0 12px rgba(15, 115, 223, 0.5),
        0 0 21px rgba(15, 115, 223, 0.9), 0 0 34px rgba(15, 115, 223, 0.8),
        0 0 54px rgba(15, 115, 223, 0.9);
    }

    to {
      text-shadow: 0 0 6px rgba(182, 211, 207, 1),
        0 0 30px rgba(182, 211, 207, 0.4), 0 0 12px rgba(15, 115, 223, 0.6),
        0 0 22px rgba(15, 115, 223, 0.8), 0 0 38px rgba(15, 115, 223, 0.9),
        0 0 60px rgba(15, 115, 223, 1);
    }
  }
```


[https://github.com/censek/HTML5-CSS3-demos/tree/master/%E9%9C%93%E8%99%B9%E6%96%87%E6%9C%AC](https://github.com/censek/HTML5-CSS3-demos/tree/master/%E9%9C%93%E8%99%B9%E6%96%87%E6%9C%AC)
