### ISSUE TITLE
[css] 第389天 除了可以用js跟踪用户信息外，如果不用js，使用纯css怎么做呢？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2348]
第389天 除了可以用js跟踪用户信息外，如果不用js，使用纯css怎么做呢？

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by mx623303468** [comment]
可以利用 css 的伪类 `:hover :active :focus` 之类的监听用户行为，然后给指定的url 发送请求。
```css
#link:active::after {

content:url('xxx/xxx?active');

}
```
