### ISSUE TITLE
[css] 第391天 使用css画个镰刀形的月亮

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2360]
第391天 使用css画个镰刀形的月亮

[我也要出题](http://web.haizlin.cn/interview/)

**Comment by yanyanlili2020** [comment]
`<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>月亮</title>
	<style type="text/css">
		.circle1 {
			background-color: yellow;
			border-radius:    50%;
			height:           100px;
			margin-left:      30px;
			position:         fixed;
			width:            100px;
			}
		.circle2 {
			background-color: #ffffff;
			border-radius:    50%;
			height:           100px;
			position:         fixed;
			width:            100px;
			}
	</style>
</head>
<body>
<div class="circle1"></div>
<div class="circle2"></div>
</body>
</html>`

![图片](https://user-images.githubusercontent.com/62490380/110752821-bc35cf80-8280-11eb-8c6e-a8a4ad85d5a4.png)

**Comment by helloskynet** [comment]
HTML:
```html
<div class="earth-moon">
      <div class="moon"></div>
      <div class="earth"></div>
</div>
```
CSS
```css
 .earth-moon{
        position: relative;
}
.moon{
        width: 100px;
        height: 100px;
        border-radius: 50px;
        background-color: yellow;
}
.earth{
        position: absolute;
        width: 110px;
        height: 110px;
        border-radius: 55px;
        top: -5px;
        left: 10px;
        background-color: white;;
}
```
复习下水平居中
```css
.earth-moon {
    position: relative;
    background-color: black;
    height: 200px;
}
.moon {
    width: 100px;
    height: 100px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translateY(-50%);
    border-radius: 50%;
    background-color: yellow;
}
.earth {
    width: 110px;
    height: 110px;
    border-radius: 50%;
    top: 50%;
    left: 50%;
    transform: translateY(-50%);
    position: absolute;
    background-color: blue;
    animation: earth-moon 10s infinite alternate-reverse;
}
@keyframes earth-moon {
    from {
      left: 20%;
    }
    to {
      left: 80%;
    }
}
```
