### ISSUE TITLE
[css] 第401天 如何使用css显示a链接的url？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2403]
第401天 如何使用css显示a链接的url？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by ferrinweb** [comment]
```css
.some-a-tag:before {
  content: attr(href);
}
```

**Comment by MrTenger** [comment]
利用伪元素的content:attr(href)

**Comment by xiongchen2012** [comment]
```css
a::after{
content: attr(href);
}
```
