### ISSUE TITLE
[css] 第407天 不用换行的标签，怎么伪元素实现换行的效果？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2431]
第407天 不用换行的标签，怎么伪元素实现换行的效果？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by wheatup** [comment]
使用`\A `换行，并且指定`white-space: pre`保留换行效果
```css
.foo::after {
  content: '123\A 456';
  white-space: pre;
}
```
