### ISSUE TITLE
[css] 第411天 用css画一个平行四边形

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2449]
第411天 用css画一个平行四边形

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by censek** [comment]
### `skew`
- `skew(x-angle,y-angle)`：沿着X轴Y轴2D倾斜旋转
- `skewX(angle)`：沿着X轴2D倾斜旋转
- `skewY(angle)`：沿着Y轴2D倾斜旋转
``` css
.parallelogram {
  margin: 30px;
  width: 200px;
  height: 100px;
  border: 1px solid slateblue;
  transform: skew(-20deg);
}
```
```html
<div class="parallelogram"></div>
```
