### ISSUE TITLE
[css] 第414天 假如css的分号写在声明块之外，将会发生什么呢？解释下原因[代码]

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2461]
第414天 假如css的分号写在声明块之外，将会发生什么呢？解释下原因[代码]

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

```html

<style>
p {color: blue};
.p1 {color: red}
.p2 {color: green}
</style>

<p class="p1">红色字体</p>
<p class="p2">绿色字体</p>

```

**Comment by Lvhaoyu** [comment]
这样写第一条规则的分号会被放到第二条规则的句首解析，导致第二条解析报错，从而略过。
```css
<style>
p {color: blue}
;.p1 {color: red}
.p2 {color: green}
</style>
```
