### ISSUE TITLE
[css] 第458天 @media print可以用来控制web打印样式吗？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2656]
第458天 @media print可以用来控制web打印样式吗？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by Zhangtiedan** [comment]
不可以

**Comment by zhaofeipeter** [comment]
可以

**Comment by censek** [comment]
可以。

```css
@media print {
  @page {
    margin: 20mm 10mm 15mm 10mm;
  }
}
```
