### ISSUE TITLE
[css] 第509天 flex:1与flex:auto有什么区别？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2869]
第509天 flex:1与flex:auto有什么区别？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by censek** [comment]
```css
div{
    flex: auto;
}
/* 等同于 */
div{
    flex-grow: 1;
    flex-shrink: 1;
    flex-basis: auto;
}
```
```css
div{
    flex: 1;
}
/* 等同于 */
div{
    flex-grow: 1;
    flex-shrink: 1;
    flex-basis: 0%;
}
```
