### ISSUE TITLE
[css] 第511天 如何取消同级li的最后一个li标签的右边距？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2878]
第511天 如何取消同级li的最后一个li标签的右边距？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by wheatup** [comment]
可以先总体设置右边距，然后再单独取消最后一个li元素的右边距
```css
li {
  margin-right: 10px;
}

li:last-of-type {
  margin-right: initial;
}
```
---
也可以直接给除了最后一个li以外的元素设置右边距
```css
  li:not(:last-of-type) {
    margin-right: 10px;
  }
```

**Comment by censek** [comment]
`:last-child` 选择器


```css
li:last-child {
  margin-right: 0 
}
```
