### ISSUE TITLE
[css] 第520天 为什么代码中两个`display`属性为`inline-block`的元素之间有多余字符（包括换行、制表符等）会造成页面中这两个元素之间有空隙？解决方案是什么？替代方案又都有哪些？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2919]
第520天 为什么代码中两个`display`属性为`inline-block`的元素之间有多余字符（包括换行、制表符等）会造成页面中这两个元素之间有空隙？解决方案是什么？替代方案又都有哪些？

作者：jw-12138

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

```css
.item{ display: inline-block; }
```  
  
```html
<span class="item">aaa</span>
<span class="item">bbb</span>
```

**Comment by censek** [comment]
解决方案：
- 把两个`<span>`写在一行
  ```html
    <span class="item">aaa</span><span class="item">bbb</span>
  ```
- `float`浮动
  ```css
  .item {
    display: inline-block;
    float: left;
  }
  ```
