### ISSUE TITLE
[css] 第526天 使用纯css布局中一个“王”字

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2953]
第526天 使用纯css布局中一个“王”字

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by longhui520** [comment]
```css
    .wang{
        position: relative;
        width: 100px;
        height: 100px;
        margin:100px auto;
        border-bottom: 2px solid red;
        border-top: 2px solid red;
    }
    .wang::before{
        position: absolute;
        content: "";
        left:49px;
        top:0;
        width: 2px;
        height: 100px;
        background-color: red;
    }
    .wang::after{
        position: absolute;
        content:"";
        left:0;
        top:48px;
        width: 100px;
        height: 2px;
        background-color: red;
    }
  ```
