### ISSUE TITLE
[css] 第528天 给兄弟元素的标签设置红色

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#2972]
第528天 给兄弟元素的标签设置红色

#1404

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by wheatup** [comment]
```css
.target + * {
  color: red;
}
```
