### ISSUE TITLE
[css] 第551天 写一个特效：鼠标经过文字时，文字旋转360度

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3072]
第551天 写一个特效：鼠标经过文字时，文字旋转360度

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by wolichuang** [comment]
```
* {
        margin: 0;
        padding: 0;
      }
      body {
        box-sizing: border-box;
        align-items: center;
        justify-content: center;
      }
      a {
        display: block;
        width: 80px;
        height: 80px;
        border: 1px solid #eeddee;
        margin: 50px auto;
        color: #333;
        text-decoration: none;
      }
      a:hover {
        animation: fly01 1s infinite;
      }
      @keyframes fly01 {
        from {
          transform: rotate(0deg);
        }
        to {
          transform: rotate(360deg);
        }
      }
```

**Comment by ferrinweb** [comment]
```css
.text-hover-r360{
  transition: transform 1s linear;
}
.text-hover-r360:hover{
  transform: rotate(360deg);
}
```
