### ISSUE TITLE
[css] 第555天 使用css实现模糊的效果

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3088]
第555天 使用css实现模糊的效果

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by ferrinweb** [comment]
```css
body {
  filter: blur(10px);
}
```
