### ISSUE TITLE
[html] 第610天 写一个布局，它的宽度是不固定的100%，如果让它的宽度始终是高度的一半呢？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3312]
第610天 写一个布局，它的宽度是不固定的100%，如果让它的宽度始终是高度的一半呢？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by wheatup** [comment]
利用`padding`和`margin`使用百分比时以元素宽度为基准的特性，可以以此固定元素的宽高比：

```html
<div class="ratio" style="--ratio: 2;"></div>
```

```css
.ratio {
  background-color: salmon;
}

.ratio::before {
  content: '';
  display: block;
  padding-top: calc(1 / var(--ratio) * 100%);
}
```

**Comment by shuaibichuang** [comment]
width:50vh;
height:100vh;

**Comment by FreddyZeng** [comment]
em,宽度为1.0,高度为0.5

**Comment by wind8866** [comment]
原理：padding-bootom如果是百分比，是相对于父元素宽度的百分比。
```html
<div class="wh-wrap">
  <div class="width-height2"></div>
</div>
```
```css
.wh-wrap {
  width: 100px;
}
.width-height2 {
  width: 100%;
  padding-bottom: 200%;
  background: #daf;
}
```
