### ISSUE TITLE
[html] 第628天 写一个垂直的三栏布局，第一栏固定顶部，中间铺满，第三栏固定底部

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3385]
第628天 写一个垂直的三栏布局，第一栏固定顶部，中间铺满，第三栏固定底部

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by lhs80** [comment]
-WEBKIT-BOX

**Comment by xmzlwyq** [comment]
好像有几种写法
我个人比较喜欢的是，
 <style>
        html,
        body {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
        }
        
        .top-level {
            position: fixed;
            left: 0;
            right: 0;
            height: 50px;
            z-index: 999;
        }
        
        #top {
            top: 0;
        }
        
        #center {
            position: relative;
            height: 100%;
            padding: 50px 0;
        }
        
        #bottom {
            bottom: 0;
        }
    </style>

body部分
  <div id="top" class="top-level">
  </div>
  <div id="center">
  </div>
  <div id="bottom" class="top-level">
  </div>

**Comment by wind8866** [comment]
```html
<div class="top">菜单</div>
<div class="main">
  内容
</div>
<div class="bottom">版权</div>
```
```css
.main {
  height: 300vh;
  background: #eee;
}
body {
  padding: 0;
  margin: 0;
}
.top {
  position: sticky;
  top: 0;
  width: 100%;
  height: 50px;
  background: #eac;
}
.bottom {
  position: sticky;
  bottom: 0;
  width: 100%;
  height: 50px;
  background: #cea;
}
```
