### ISSUE TITLE
[css] 第655天 用css隐藏input的光标

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3501]
第655天 用css隐藏input的光标

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by thainl** [comment]
```css
input {
  color: transparent;
  text-shadow: 0 0 0 #000;
}
````

**Comment by wheatup** [comment]
```css
input {
  caret-color: transparent;
}
```
