### ISSUE TITLE
[html] 第697天 如何禁止HTML页面滚动？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3679]
第697天 如何禁止HTML页面滚动？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by helloskynet** [comment]
```css
html{
    overflow:hidden;
}
```
