### ISSUE TITLE
[css] 第712天 css如何实现滚动条隐藏但鼠标仍然可以滚动？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3744]
第712天 css如何实现滚动条隐藏但鼠标仍然可以滚动？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by alanhg** [comment]
```css
body::-webkit-scrollbar {
        display: none;
      }
```
