### ISSUE TITLE
[css] 第723天 写一个风扇转动的动画

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3789]
第723天 写一个风扇转动的动画

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by shuxhan** [comment]
之前在掘金看到的一串代码
```css
{
    transform: rotate(666turn);
    transition-delay: 1s;
    transition-property: all;
    transition-duration: 59s;
    transition-timing-function: cubic-bezier(.34,0,.84,1);
}
```
