### ISSUE TITLE
[css] css属性名和属性值是否区分大小写？

### ISSUE THREAD

**Issue by Drowned-fish** [haizlin/fe-interview#3796]
众所周知，一个典型的css如下: 
```css
   .demo {
       font-size: 16px;
   }
```
请问，属性名(例如font-size)是否区分大小写？属性值(例如16px)是否区分大小写？请给出具体理由
