### ISSUE TITLE
[css] 第743天 使用css画一个椭圆

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3873]
第743天 使用css画一个椭圆

#2739

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by shuxhan** [comment]
```html
<!-- html -->
<div></div>
```
```css
/* css */
div {
    border: 1px solid #000;
    width: 100px;
    height: 50px;
    border-radius: 50%;
}
```
