### ISSUE TITLE
[html] 第765天 写出一个可滚动的区域，但要隐藏滚动条

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#3970]
第765天 写出一个可滚动的区域，但要隐藏滚动条

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by shuxhan** [comment]
```html
<div class="div">
    1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>
    1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>
    1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>
    1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>
    1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>
</div>
```
```css
.div {
    background: #444;
    color: #fff;
    width: 300px;
    height: 300px;
    scrollbar-width: none;
    -ms-overflow-style: none;
    overflow: auto;
}
.div::-webkit-scrollbar {
    display: none;
}
```
