### ISSUE TITLE
[css] 第773天 把鼠标指针放到某div元素上，其宽度会从50px逐渐变为200px

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#4007]
第773天 把鼠标指针放到某div元素上，其宽度会从50px逐渐变为200px

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by shuxhan** [comment]
[>> 点击查看 demo](https://code.shuxhan.com/20210528.html)   

（将鼠标悬浮在黑色方块之上）

```css
.demo {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%,-50%);
      background: #444;
      width: 50px;
      height: 50px;
      transition: all 0.5s linear;
    }
    .demo:hover {
      width: 200px;
}
```
```html
<div class="demo"></div>
```
