### ISSUE TITLE
[css] 第780天 css中如何定义及使用变量？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#4035]
第780天 css中如何定义及使用变量？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by shuxhan** [comment]
```css
:root {
    --size: 20px;
}

body {
    font-size: var(--size);
}
```
