### ISSUE TITLE
[css] 第991天 你有使用过css中的contrast函数吗？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#4899]
第991天 你有使用过css中的contrast函数吗？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by xiaoguo-ui** [comment]
CSS中的contrast()函数可以调整一个元素的对比度。对比度指的是图像中最亮和最暗区域之间的差异程度。该函数接受一个参数，表示对比度的百分比调整量。

使用示例：
```css
/* 将对比度增加50% */
.element {
  filter: contrast(150%);
}
```

支持的参数值范围为 -100% 到 100%。默认值为 100%，表示无调整。

需要注意的是，contrast()函数是一个滤镜函数，需要使用filter属性来应用。它可以应用于任何元素，包括图片、文本和背景等。

示例：
```css
/* 将图片的对比度减小50% */
img {
  filter: contrast(50%);
}
```
