### ISSUE TITLE
[css] 第993天 请使用css实现当<a>中没有文本而href不为空的时候，显示它的链接

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#4907]
第993天 请使用css实现当<a>中没有文本而href不为空的时候，显示它的链接

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by Jie6** [comment]
```css
a:empty[href]::after {
    content: attr(href);
    display: inline-block;
}
```

有个缺陷，`<a href></a>`也能匹配上，改成`a:empty[href*="."]::after`又不是很严谨
