### ISSUE TITLE
[css] 第996天 你有使用过css的background-clip属性吗？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#4919]
第996天 你有使用过css的background-clip属性吗？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by xiaoguo-ui** [comment]
CSS中的background-clip属性用于指定元素的背景图像或背景颜色的绘制区域。

该属性可以取以下几个值：

1. border-box：背景绘制在边框区域，不会延伸到边框之外。
2. padding-box：背景绘制在内边距区域，不会延伸到边框和内容区域之外。
3. content-box：背景绘制在内容区域，不会延伸到边框和内边距区域之外。
4. text：仅适用于文本元素，背景仅绘制在文字区域，不会延伸到边框、内边距或其他文本周围。

示例代码：
```css
.example {
  background-image: url('example.jpg');
  background-clip: border-box;
}
```

在上述示例中，将一个背景图像应用于元素，并将background-clip属性设置为border-box，这将使背景图像绘制在元素的边框区域内，不会延伸到边框之外。
