### ISSUE TITLE
[css] 第76天 用CSS画出一个任意角度的扇形，可以写多种实现的方法

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#527]
第76天 用CSS画出一个任意角度的扇形，可以写多种实现的方法

**Comment by liuxiaole** [comment]
四个半圆叠加，过半调整z-index：
https://codepen.io/liuxiaole-the-sasster/full/RzQBKV

**Comment by git710** [comment]
任意角度不太会,需要变量?使用canvas或者svg很容易实现任意角度扇形
```html
<div class="san1"></div>
<div class="san2"></div>
```
```css
.san1{
    border: 100px solid transparent;
    border-top-color: #f00;
    width: 0;
    border-radius: 100px;
}

.san2{
    width: 100px;
    height: 100px;
    background-color: #f00;
    border-radius: 100px 0 0;
}
```

**Comment by lu-xiansen** [comment]
###CSS代码
先画一个原,外加两个绝对定位的半圆
扇形可以通过两个半圆作为遮罩旋转来露出相应的角度实现
这只能切除180°以内的扇形
超过180°的扇形,就把圆作为底色,两个遮罩作为扇形的组成部分

不知道描述的好不好理解,但确实能实现任意角度的扇形了
```css
.contain {
			position: relative;
			width: 200px;
			height: 200px;
		}
		.main {
			height: 100%;
			background: lightgreen;
			border-radius: 100px;
		}
		.common {
			position: absolute;
			top: 0;
			width: 50%;
			height: 100%;
		}
		.mask1 {
			transform: rotate(83deg);
			border-radius: 100px 0 0 100px;
			left: 0;
			transform-origin: right center;
			background: red;
		}
		.mask2 {
			transform: rotate(-76deg);
			transform-origin: left center;
			left: 100px;
			border-radius: 0 100px 100px 0;
			background: blue;
		}
```
```HTML
        <div class="contain">
		<div class="main"></div>
		<div class="mask1 common"></div>
		<div class="mask2 common"></div>
	</div>
```
