### ISSUE TITLE
[css] 第1372天 如何使用CSS实现隐藏滚动条但内容可以滚动？

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#5329]
第1372天 如何使用CSS实现隐藏滚动条但内容可以滚动？

[3+1官网](http://www.h-camel.com/index.html)

[我也要出题](http://www.h-camel.com/contribution.html)

**Comment by SanjeevSingh08** [comment]
u need to use overflow hidden in the body section

**Comment by SanjeevSingh08** [comment]
你需要使用隐藏在正文部分的溢出

**Comment by ShihHsing** [comment]
可以使用CSS的伪元素 `::-webkit-scrollbar` 和 `::-webkit-scrollbar-track` 以及 `::-webkit-scrollbar-thumb` 来实现隐藏滚动条但内容可以滚动的效果，具体步骤如下：

将 `::-webkit-scrollbar` 的宽度设置为0，这样就隐藏了滚动条。
将 `::-webkit-scrollbar-track` 的背景色设置为和页面背景色一致，这样滚动条区域看起来就和页面背景一样了。
将 `::-webkit-scrollbar-thumb` 的背景色设置为和需要滚动的内容一致，这样滚动条拖动区域看起来就和滚动的内容一样了。
具体的CSS代码如下：

```css
/* 隐藏滚动条 */
::-webkit-scrollbar {
  width: 0;
}

/* 滚动条区域背景色 */
::-webkit-scrollbar-track {
  background-color: #f2f2f2;
}

/* 滚动条拖动区域背景色 */
::-webkit-scrollbar-thumb {
  background-color: #ccc;
}
```

在需要滚动的元素上，只需要添加以下CSS样式即可：

```css
overflow: auto;
```

这样就可以实现隐藏滚动条但内容可以滚动的效果了。
