### ISSUE TITLE
[css] 第87天 写出几个初始化CSS的样式，并解释说明为什么要这样写

### ISSUE THREAD

**Issue by haizhilin2013** [haizlin/fe-interview#601]
第87天 写出几个初始化CSS的样式，并解释说明为什么要这样写

**Comment by dondonZh** [comment]
去除margin 和padding还有一些属性 对布局带来的影响

**Comment by xiangshuo1992** [comment]
`li {list-style: none}`
取消列表的标识符

**Comment by nowherebutup** [comment]
```css
padding:0;
nargin:0;
```
为了统一各个浏览器显示不一样的问题

**Comment by yangxy6** [comment]
```
// 自适应高度
html,
body {
  width: 100%;
  height: 100%;
}
// 清除浮动
.clearfix {
  zoom: 1;
}
.clearfix::before,
.clearfix::after {
  display: table;
  content: '';
}
.clearfix::after {
  clear: both;
}
```

**Comment by encountermm** [comment]
引用css初始化库，如；
[normalize.css](https://necolas.github.io/normalize.css/latest/normalize.css)

1. 因为浏览器的兼容问题，不同浏览器对有些标签的默认值是不同的，如果没对CSS初始化往往会出现浏览器之间的页面显示差异
2.初始化CSS样式可以提高编码质量，保持代码的统一性，如果不初始化，重复的CSS样式很多。

**Comment by webforworld** [comment]
outline:none
消除button的激活边框

**Comment by 542154968** [comment]
reset.css

**Comment by chenshijin1** [comment]
```css
/*清除元素默认的内外边距  */
* {
    margin: 0;
    padding: 0
}
/*让所有斜体 不倾斜*/
em,
i {
    font-style: normal;
}
/*去掉列表前面的小点*/
li {
    list-style: none;
}
/*图片没有边框   去掉图片底侧的空白缝隙*/
img {
    border: 0;  /*ie6*/
    vertical-align: middle;
}

/*取消链接的下划线*/
a {
    text-decoration: none;
}

/*清除浮动*/
.clearfix:after {
    visibility: hidden;
    clear: both;
    display: block;
    content: ".";
    height: 0
}

.clearfix {
    *zoom: 1
}
```
